spring.application.name=hotelbookingsystem
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=hotelbookingsystem;encrypt=true;trustServerCertificate=true
spring.datasource.username=myuser
spring.datasource.password=Test@123

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true